name: Load Test

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - run: git clone https://github.com/leollo98/Infra_CI
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.2
      
    - run: terraform -chdir=Infra_CI/env/Homolog/ init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - run: terraform -chdir=Infra_CI/env/Homolog/ apply -auto-approve -var=imagem=$TF_VAR_imagem
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_imagem: "leonardosartorello/go_ci:100"
    
    
    - name: Run Load Test
      uses: apardo04/locust-github-action@master
      id: locust
      with:
        URL:  "https://google.com"
        USERS: "50"
        RATE: "5"
        RUNTIME: "60s"
    - name: output
      run: echo ${{ steps.locust.outputs }}
