name: Load Test

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - run: git clone https://github.com/leollo98/Infra_CI
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.2
    
    - run: ls -lha
    
    - run: cd Infra_CI/env/Homolog/
      
    - run: terraform init
    
    - run: terraform apply -auto-approve
    
    
    - name: Run Load Test
      uses: apardo04/locust-github-action@master
      id: locust
      with:
        URL:  "https://google.com"
        USERS: "50"
        RATE: "5"
        RUNTIME: "60s"
    - name: output
      run: echo ${{ steps.locust.outputs }}
