name: Load Test

on: 
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - run: git clone https://github.com/leollo98/Infra_CI
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.2
      
    - run: terraform -chdir=Infra_CI/env/Homolog/ init
    
    - run: terraform -chdir=Infra_CI/env/Homolog/ apply -auto-approve
    
    - run: echo "$(terraform -chdir=Infra_CI/env/Homolog/ output -raw IP_alb)/bruno"
      id: URL
    
    - run: echo ${{  steps.URL.outputs.stdout }} 
      
    - run: sleep 30s
      
    - name: Run Load Test
      continue-on-error: true
      uses: apardo04/locust-github-action@master
      id: locust
      with:
        URL: ${{steps.URL.outputs.stdout}}
        USERS: "1"
        RATE: "5"
        RUNTIME: "60s"
      
      
    - run: terraform -chdir=Infra_CI/env/Homolog/ destroy -auto-approve 
