name: Load Test

on:
  workflow_call:

jobs:

  docker:
    defaults:
      run:
        working-directory: env/Homolog/
    runs-on: ubuntu-latest
    steps:
    - run: git clone https://github.com/leollo98/Infra_CI
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.2
      
    - run: terraform init
    
    - run: terraform apply -auto-approve
    
    
